// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2fVFtDiF_7CpmrQc-QP0T4IFaiFL79lc',
    appId: '1:674996843267:web:4acb0d0942c34657d06f36',
    messagingSenderId: '674996843267',
    projectId: 'dz-zaal',
    authDomain: 'dz-zaal.firebaseapp.com',
    storageBucket: 'dz-zaal.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBermjWHlODiKiYEWGnTkPFhgYmypHpZ4',
    appId: '1:674996843267:ios:dd55c6a2a3d2872bd06f36',
    messagingSenderId: '674996843267',
    projectId: 'dz-zaal',
    storageBucket: 'dz-zaal.firebasestorage.app',
    iosBundleId: 'com.example.dzZaal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2fVFtDiF_7CpmrQc-QP0T4IFaiFL79lc',
    appId: '1:674996843267:web:f6da061b5a935005d06f36',
    messagingSenderId: '674996843267',
    projectId: 'dz-zaal',
    authDomain: 'dz-zaal.firebaseapp.com',
    storageBucket: 'dz-zaal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBermjWHlODiKiYEWGnTkPFhgYmypHpZ4',
    appId: '1:674996843267:ios:dd55c6a2a3d2872bd06f36',
    messagingSenderId: '674996843267',
    projectId: 'dz-zaal',
    storageBucket: 'dz-zaal.firebasestorage.app',
    iosBundleId: 'com.example.dzZaal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMVr6zncSrNulN9lXOa7dqQi8OWQoe_E',
    appId: '1:674996843267:android:b3643be93809bfe0d06f36',
    messagingSenderId: '674996843267',
    projectId: 'dz-zaal',
    storageBucket: 'dz-zaal.firebasestorage.app',
  );

}